apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: worker
  template:
    metadata:
      labels:
        component: worker
    spec:
      containers:
        - name: worker
          image: algorhythm92/multi-worker
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service # metadata.name in redis-cluster-ip-service.yml
            - name: REDIS_PORT
              value: '6379'                     # spec.ports.targetPort in redis-cluster-ip-service.yml